CREATE SCHEMA IF NOT EXISTS excel_table AUTHORIZATION postgres;

-- Permissions

GRANT ALL ON SCHEMA excel_table TO postgres;
GRANT ALL ON SCHEMA excel_table TO excel_table;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA excel_table GRANT ALL ON SEQUENCES TO excel_table;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA excel_table GRANT USAGE ON TYPES TO sexcel_table;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA excel_table GRANT EXECUTE ON FUNCTIONS TO excel_table;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA excel_table GRANT ALL ON TABLES TO excel_table;